### ISSUE TITLE
Add Fossil Island Bank as possible Nearest Bank

### ISSUE THREAD

**Issue by rokaHakor** [itsdax/Runescape-Web-Walker-Engine#111]
Could the Fossil Island bank be added as a possible nearest bank? Sure the bank chest might not be built but you could just check the quest var state for Bone Voyage since I assure you 99% of people who've finished Bone Voyage have the bank built and if they don't then they should build it lol.

**Comment by FALSkills** [comment]
I went ahead and grabbed the varbit that is associated with the museum camp bank being built and added it c495a2e443f21c51da083e390ab87ea54f9ac9ae.  For future note, I will not add anything that will potentially break scripts for specific users just because "they should have done it" in a specific way.
