### ISSUE TITLE
Support for Sophanem dungeon ladder request

### ISSUE THREAD

**Issue by Shardzx** [itsdax/Runescape-Web-Walker-Engine#137]
Hello, 
Sophanem dungeon tile movement is working great with the daxwalker. Would it be possible to add support for the ladder to make it fully functional for this dungeon?

![java_H0Tu3kSeoP](https://user-images.githubusercontent.com/69726907/174802952-f6366935-d352-494e-99ea-f956304e3a94.png)

![java_DLrhXBc797](https://user-images.githubusercontent.com/69726907/174802974-accbc1c3-a843-4a74-b252-4ca38e1de747.png)

![java_yERwH6gvYm](https://user-images.githubusercontent.com/69726907/174802987-bb97f108-7916-46cb-9b45-b330f2100272.png)

**Comment by FALSkills** [comment]
Funny enough, I had previously added all the nodes for this bank from the topside but forgot to add the collision for the bank itself.  This should be live the next time @itsdax deploys.  

I added some collision for the dungeon below, however I am not going to link the dungeon area to the bank at this time.  Navigating the dungeon serves very little purpose outside of quest related activities, and adding the nodes there will likely require special cases to be created since it has two ladders next to each other that behave unexpectedly (the ladder going "up" returns to the rest of the regular map, and the ladder going "down" actually goes up 2 floors and travels several hundred tiles away)
