### ISSUE TITLE
Garden of death exit support for daxwalker

### ISSUE THREAD

**Issue by Shardzx** [itsdax/Runescape-Web-Walker-Engine#219]
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/189edb5b-d7f7-45f6-98eb-d31bfea8ad6e)

Daxwalker will keep on trying to teleport when trying to escape from this place,however it keeps on getting stuck on loop.

![AnyDesk_2Nbb3vEeLq](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/fac7edb3-73ab-43e2-b01e-32eb2009be33)

https://pastebin.com/6tqRrwF3

**Comment by FALSkills** [comment]
This really ought to be handled script-side.  If you are running a Garden of Death script, it should leave the dungeon before considering the quest "complete".   My reasons for that (and feel free to correct me if I'm wrong) are as below:

- there is no real reason to return to this location
- there is no reliable way to determine that we cannot teleport (aside from an area check).  no varbits update when you enter or leave the area.

If you insist that the area gets added, then this is the information I'll need:

- Collision data, can be gathered by running this function (it puts a .cdata file in your .tribot folder) while in the dungeon: `CollisionFileMaker.getCollisionData();`
- Area changes - the tile that you would interact with the hole from, as well as the tile that you would arrive at inside of the dungeon.  both tiles need to be walkable, and not that tile of the object.
- an RSArea object that would include the entirety of the dungeon so that I can implement a blacklist of areas that we cannot teleport from

**Comment by Shardzx** [comment]
Thank you for the quick answer. I've configured it to run AIO when I encounter this situation,as it does exit the dungeon. It's not worth mapping this dungeon since it has no other use besides the quest.
